services:
  app:
    build: .
    environment:
      - TZ=UTC
    working_dir: /app
    ports:
      - "4000:4000"  # telnet
      - "4001:4001"  # webclient/ws
    volumes:
      - ./:/app
      - staticfiles:/app/staticfiles
    restart: unless-stopped
    command: ["/app/start_evennia.sh"]

volumes:
  staticfiles:

